spring:
  application:
     name: api-gateway

  cloud:
    gateway:
       routes:
         - id: patient-service
           uri: lb://PATIENT-SERVICE
           predicates:
             - Path=/api/v1/patient/**
                            
           filters:
             - StripPrefix=2

         - id: borrower-service
           uri: lb://BORROWER-SERVICE
           predicates:
             - Path=/api/v1/borrower/**

           filters:
             - StripPrefix=2
             - AddRequestHeader=X-Pqr-Header, Man

eureka:
   client:
     service-url:
        defaultZone: http://localhost:8761/eureka


server:
  port: 8010